### PR TITLE
added two resource links for NodeJS registration application and Mongo DB set up

### PR DESCRIPTION
**Pull request by pakawaka1**

### CODE REVIEW

**Comment by pakawaka1** [comment]
I used these two resources to help me further my understanding of the MEAN stack.  They were very useful while working on the Iris-App application.

**Review by benreckas — CHANGES_REQUESTED** [review]
Could you remove the unnecessary lines from lines 78-95? It looks we want the links to the resources but not necessarily all of the patron and donation stuff.

**Comment by benreckas** [comment]
It also looks like the Udemy link is broken. Is it a new course to be added? You might check to see if it's listed already.

**Comment by pakawaka1** [comment]
Fixes in tact.  Please review.

**Review by benreckas — APPROVED** [review]
Nice!

**Pull request merged**
